version: '3.9'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: go=app-ms2:latest
    ports:
      - "8080:8080"
    restart: always
    networks:
      - web

networks:
  web:
